version: '3.4'

services:

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_catalogdb_data:/data/db
    command: ["mongod", "--port", "27017"]

  catalogbranddb:
    container_name: catalogbranddb
    restart: always
    ports:
        - "27018:27018"
    volumes:
        - ./mongo_catalogbranddb_data:/data/db
    command: ["mongod", "--port", "27018"]

  catalogcategorydb:
    container_name: catalogcategorydb
    restart: always
    ports:
        - "27019:27019"
    volumes:
        - ./mongo_catalogcategorydb_data:/data/db
    command: ["mongod", "--port", "27019"]

  catalogcommentdb:
    container_name: catalogcommentdb
    restart: always
    ports:
        - "27020:27020"
    volumes:
        - ./mongo_catalogcommentdb_data:/data/db
    command: ["mongod", "--port", "27020"]


  useraccountdb:
    container_name: useraccountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - ./postgres_useraccountdb_data:/var/lib/postgresql/data/


  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "AWS:GrpcUrl=http://aws.grpc"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  catalogbrand.api:
    container_name: catalogbrand.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogbranddb:27018"
    depends_on:
      - catalogbranddb
    ports:
      - "8001:80"

  catalogcategory.api:
    container_name: catalogcategory.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogcategorydb:27019"
      - "AWS:GrpcUrl=http://aws.grpc"
    depends_on:
      - catalogcategorydb
    ports:
      - "8002:80"

  catalogcomment.api:
    container_name: catalogcomment.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogcommentdb:27020"
      - "GrpcSettings:CatalogUrl=http://catalog.grpc"
      - "GrpcSettings:UserUrl=http://useraccount.grpc"
    depends_on:
      - catalogcommentdb
    ports:
      - "8003:80"


  catalog.grpc:
    container_name: catalog.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8004:80"
     

  useraccount.api:
    container_name: useraccount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=User ID=admin;Password=admin1234;Server=useraccountdb;Port=5432;Database=useraccountdb;Integrated Security=true;Pooling=true;"
      - "AWS:GrpcUrl=http://aws.grpc"
    depends_on:
      - useraccountdb
    ports:
      - "8005:80"


  useraccount.grpc:
    container_name: useraccount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=User ID=admin;Password=admin1234;Server=useraccountdb;Port=5432;Database=useraccountdb;Integrated Security=true;Pooling=true;"
    depends_on:
      - useraccountdb
    ports:
      - "8006:80"

  aws.api:
    container_name: aws.api
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "GrpcSettings:CatalogCategoryUrl=http://catalogcategory.grpc"
      - "GrpcSettings:UserAccountUrl=http://useraccount.grpc"
      - "GrpcSettings:CatalogUrl=http://catalog.grpc"
    ports:
      - "8007:80"

  catalogcategory.grpc:
    container_name: catalogcategory.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogcategorydb:27019"
    depends_on:
      - catalogcategorydb
    ports:
      - "8009:80"

  aws.grpc:
    container_name: aws.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8010:80"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
