version: '3.4'

services:

  catalogdb:
    image: mongo

  catalogbranddb:
    image: mongo

  catalogcategorydb:
    image: mongo

  catalogcommentdb:
    image: mongo


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  catalogbrand.api:
    image: ${DOCKER_REGISTRY-}catalogbrandapi
    build:
      context: .
      dockerfile: Services/CatalogBrand/CatalogBrand.API/Dockerfile


  catalogcategory.api:
    image: ${DOCKER_REGISTRY-}catalogcategoryapi
    build:
      context: .
      dockerfile: Services/CatalogCategory/CatalogCategory.API/Dockerfile


  catalogcomment.api:
    image: ${DOCKER_REGISTRY-}catalogcommentapi
    build:
      context: .
      dockerfile: Services/CatalogComment/CatalogComment.API/Dockerfile


  catalog.grpc:
    image: ${DOCKER_REGISTRY-}cataloggrpc
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.GRPC/Dockerfile

